CREATE TABLE IF NOT EXISTS "planicamping_local_activity" (
	"ID" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "planicamping_local_activity_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Title" varchar(256) NOT NULL,
	"Description" text,
	"Location" varchar(255) NOT NULL,
	"Category" varchar(100),
	"Image" varchar(512),
	"Distance" varchar(50),
	"Duration" varchar(50),
	"ExternalUrl" varchar(512),
	"Campings" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "planicamping_must_see_activity" (
	"ID" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "planicamping_must_see_activity_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Title" varchar(256) NOT NULL,
	"Description" text,
	"Location" varchar(255) NOT NULL,
	"Image" varchar(512),
	"Distance" varchar(50),
	"Duration" varchar(50),
	"ExternalUrl" varchar(512),
	"Campings" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "local_title_idx" ON "planicamping_local_activity" USING btree ("Title");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "local_camping_idx" ON "planicamping_local_activity" USING btree ("Campings");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "local_category_idx" ON "planicamping_local_activity" USING btree ("Category");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "must_see_title_idx" ON "planicamping_must_see_activity" USING btree ("Title");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "must_see_camping_idx" ON "planicamping_must_see_activity" USING btree ("Campings");