-- Add campsite activities
INSERT INTO "planicamping_campsite_activity" ("Title", "infos_description", "Campings", "Contenu_date", "Contenu_time", "useful_duration")
VALUES
  -- Cap de Bréhat (PLOUEZEC)
  ('Visite guidée du phare', 'Découvrez l''histoire fascinante du phare et profitez d''une vue panoramique exceptionnelle sur l''archipel de Bréhat et la côte.', 'Cap de Bréhat', '2025-07-15', '10:00', '1h30'),
  ('Atelier de cuisine bretonne', 'Apprenez à préparer des spécialités bretonnes traditionnelles avec notre chef local.', 'Cap de Bréhat', '2025-07-16', '14:00', '2h'),
  ('Tournoi de pétanque', 'Participez à notre tournoi amical de pétanque et tentez de remporter le trophée du camping!', 'Cap de Bréhat', '2025-07-17', '16:00', '2h'),
  ('Randonnée côtière', 'Explorez les sentiers côtiers avec un guide naturaliste et découvrez la faune et flore locales.', 'Cap de Bréhat', '2025-05-15', '09:00', '3h'),
  ('Initiation à la voile', 'Découvrez les bases de la navigation à voile dans un cadre idyllique avec nos moniteurs diplômés.', 'Cap de Bréhat', '2025-05-20', '14:00', '2h30'),
  ('Soirée contes marins', 'Plongez dans l''univers maritime breton à travers des contes et légendes de la mer.', 'Cap de Bréhat', '2025-06-05', '20:30', '1h30'),
  ('Atelier crêpes et galettes', 'Apprenez les secrets de fabrication des véritables crêpes et galettes bretonnes.', 'Cap de Bréhat', '2025-06-12', '16:00', '2h'),
  ('Marché artisanal nocturne', 'Découvrez les produits locaux et l''artisanat breton lors de notre marché estival.', 'Cap de Bréhat', '2025-07-25', '18:00', '4h'),
  ('Excursion à l''île de Bréhat', 'Journée complète sur l''île de Bréhat, joyau de la côte d''Armor.', 'Cap de Bréhat', '2025-08-02', '08:30', '8h'),
  ('Concours de châteaux de sable', 'Amusement familial sur la plage avec prix pour les créations les plus originales.', 'Cap de Bréhat', '2025-08-10', '15:00', '2h'),
  ('Observation des étoiles', 'Soirée astronomie avec télescopes et commentaires d''un astronome amateur passionné.', 'Cap de Bréhat', '2025-08-15', '22:00', '2h'),
  ('Cours de photographie marine', 'Perfectionnez vos techniques de photographie de paysages maritimes.', 'Cap de Bréhat', '2025-08-20', '16:00', '3h'),
  ('Atelier matelotage', 'Initiez-vous à l''art des nœuds marins et leurs utilisations.', 'Cap de Bréhat', '2025-09-05', '14:00', '1h30'),
  
  -- Manoir de Ker an Poul (SARZEAU)
  ('Soirée fruits de mer', 'Dégustation de fruits de mer frais de la région accompagnés de vins locaux.', 'Manoir de Ker an Poul', '2025-07-20', '19:00', '3h'),
  ('Excursion au Golfe du Morbihan', 'Découverte des îles du Golfe du Morbihan en bateau avec arrêt sur l''île aux Moines.', 'Manoir de Ker an Poul', '2025-07-22', '09:00', '5h'),
  ('Concert de musique traditionnelle', 'Soirée musicale avec des artistes locaux jouant de la musique traditionnelle bretonne.', 'Manoir de Ker an Poul', '2025-07-24', '20:30', '2h'),
  ('Atelier de pêche', 'Initiation aux techniques de pêche locales avec un pêcheur expérimenté.', 'Manoir de Ker an Poul', '2025-05-25', '07:00', '3h'),
  ('Cours de danse bretonne', 'Apprenez les pas de base des danses traditionnelles bretonnes.', 'Manoir de Ker an Poul', '2025-06-10', '18:00', '2h'),
  ('Randonnée vélo dans la presqu''île', 'Découvrez les plus beaux sites de la presqu''île de Rhuys à vélo.', 'Manoir de Ker an Poul', '2025-06-15', '09:30', '4h'),
  ('Visite du château de Suscinio', 'Excursion guidée au majestueux château médiéval de Suscinio.', 'Manoir de Ker an Poul', '2025-06-22', '14:00', '3h'),
  ('Séance de yoga face à la mer', 'Moment de détente et bien-être face au magnifique Golfe du Morbihan.', 'Manoir de Ker an Poul', '2025-07-05', '08:00', '1h'),
  ('Atelier artisanat local', 'Initiez-vous à un savoir-faire traditionnel breton avec des artisans locaux.', 'Manoir de Ker an Poul', '2025-07-15', '15:00', '2h30'),
  ('Soirée contes et légendes du Morbihan', 'Plongez dans le folklore local à travers des histoires captivantes.', 'Manoir de Ker an Poul', '2025-08-01', '21:00', '1h30'),
  ('Tournoi de beach volleyball', 'Compétition amicale sur notre terrain de beach volleyball.', 'Manoir de Ker an Poul', '2025-08-10', '16:00', '3h'),
  ('Excursion ornithologique', 'Observation des oiseaux du Golfe du Morbihan avec un guide naturaliste.', 'Manoir de Ker an Poul', '2025-08-18', '07:30', '3h'),
  ('Croisière au coucher du soleil', 'Navigation dans le Golfe pour admirer un spectaculaire coucher de soleil.', 'Manoir de Ker an Poul', '2025-08-25', '20:00', '2h'),
  
  -- Domaine de Bréhadour (GUÉRANDE)
  ('Visite des marais salants', 'Découvrez le métier de paludier et l''histoire du sel de Guérande avec un guide expert.', 'Domaine de Bréhadour', '2025-08-05', '10:00', '2h30'),
  ('Atelier fabrication de sel', 'Initiez-vous à la récolte et à la préparation du sel de Domaine de Bréhadour.', 'Domaine de Bréhadour', '2025-08-06', '15:00', '1h30'),
  ('Balade à vélo dans les marais', 'Parcourez les marais salants à vélo sur un circuit balisé avec points de vue exceptionnels.', 'Domaine de Bréhadour', '2025-08-08', '09:00', '3h'),
  ('Visite guidée de la cité médiévale', 'Découvrez l''histoire fascinante de la cité fortifiée de Domaine de Bréhadour.', 'Domaine de Bréhadour', '2025-05-10', '10:30', '2h'),
  ('Atelier cuisine au sel', 'Apprenez à cuisiner avec le célèbre sel de Domaine de Bréhadour et ses variétés.', 'Domaine de Bréhadour', '2025-05-20', '16:00', '2h'),
  ('Randonnée dans la Brière', 'Excursion guidée dans le Parc Naturel Régional de Brière.', 'Domaine de Bréhadour', '2025-06-05', '09:00', '4h'),
  ('Initiation au char à voile', 'Découvrez les sensations du char à voile sur les plages de La Baule.', 'Domaine de Bréhadour', '2025-06-15', '14:00', '2h'),
  ('Visite d''une saline traditionnelle', 'Explorez une saline en activité et rencontrez un paludier passionné.', 'Domaine de Bréhadour', '2025-07-01', '10:00', '2h'),
  ('Atelier photographie nature', 'Captez la beauté des marais salants avec les conseils d''un photographe professionnel.', 'Domaine de Bréhadour', '2025-07-10', '17:00', '3h'),
  ('Soirée astronomie', 'Observation du ciel étoilé depuis les marais avec un astronome amateur.', 'Domaine de Bréhadour', '2025-07-20', '22:00', '2h'),
  ('Excursion à La Baule', 'Journée détente sur la célèbre plage de La Baule avec activités nautiques.', 'Domaine de Bréhadour', '2025-08-15', '09:30', '6h'),
  ('Concert de musique celtique', 'Soirée festive aux sonorités celtiques avec musiciens locaux.', 'Domaine de Bréhadour', '2025-08-20', '21:00', '2h30'),
  ('Balade contée au crépuscule', 'Promenade dans les marais au coucher du soleil avec contes et légendes locales.', 'Domaine de Bréhadour', '2025-08-25', '20:30', '1h30'),
  
  -- La Pointe Saint-Gildas (La Pointe Saint-Gildas)
  ('Initiation au surf', 'Cours d''initiation au surf pour tous niveaux avec instructeurs certifiés.', 'La Pointe Saint-Gildas', '2025-08-12', '11:00', '2h'),
  ('Découverte de la pêche à pied', 'Apprenez à identifier et à récolter les coquillages et crustacés à marée basse.', 'La Pointe Saint-Gildas', '2025-08-14', '14:30', '1h30'),
  ('Soirée contes et légendes', 'Laissez-vous transporter par les histoires et légendes de la région racontées autour d''un feu de camp.', 'La Pointe Saint-Gildas', '2025-08-16', '21:00', '1h30'),
  ('Visite du sémaphore', 'Découvrez l''histoire et le fonctionnement du sémaphore de la Pointe Saint-Gildas.', 'La Pointe Saint-Gildas', '2025-05-15', '10:00', '1h30'),
  ('Randonnée côtière', 'Parcourez le sentier des douaniers avec un guide naturaliste passionné.', 'La Pointe Saint-Gildas', '2025-05-25', '14:00', '3h'),
  ('Atelier cuisine de la mer', 'Apprenez à préparer et cuisiner les produits de la mer locale.', 'La Pointe Saint-Gildas', '2025-06-05', '16:00', '2h30'),
  ('Initiation au paddle', 'Découvrez le stand-up paddle dans les criques abritées de la côte.', 'La Pointe Saint-Gildas', '2025-06-15', '10:30', '2h'),
  ('Sortie observation des oiseaux marins', 'Identifiez les nombreuses espèces d''oiseaux qui peuplent notre littoral.', 'La Pointe Saint-Gildas', '2025-07-01', '08:00', '3h'),
  ('Atelier création de cerf-volant', 'Fabriquez votre propre cerf-volant et testez-le sur la plage.', 'La Pointe Saint-Gildas', '2025-07-10', '15:00', '2h'),
  ('Excursion à Pornic', 'Découverte de la charmante ville côtière de Pornic et son port.', 'La Pointe Saint-Gildas', '2025-07-20', '09:00', '5h'),
  ('Concours de châteaux de sable', 'Compétition familiale sur la plage avec prix pour les plus belles créations.', 'La Pointe Saint-Gildas', '2025-08-01', '15:00', '2h'),
  ('Concert acoustique en plein air', 'Soirée musicale sous les étoiles avec artistes locaux.', 'La Pointe Saint-Gildas', '2025-08-20', '21:00', '2h'),
  ('Atelier marin pour enfants', 'Activités ludiques autour de la mer pour les 5-12 ans.', 'La Pointe Saint-Gildas', '2025-08-25', '10:00', '2h'),
  
  -- L'Océan & Spa (L''Océan & Spa)
  ('Dégustation de vins locaux', 'Découverte des vins de l''île de Ré avec un sommelier expert.', 'L''Océan & Spa', '2025-07-10', '18:00', '2h'),
  ('Atelier bien-être', 'Séance de yoga sur la plage suivie d''une initiation aux techniques de relaxation.', 'L''Océan & Spa', '2025-07-12', '08:00', '1h30'),
  ('Balade à cheval', 'Découvrez les plages et forêts de l''île de Ré à cheval, idéal pour tous niveaux.', 'L''Océan & Spa', '2025-07-14', '10:00', '2h'),
  ('Visite des marais salants', 'Découverte du métier de saunier et dégustation de fleur de sel.', 'L''Océan & Spa', '2025-05-10', '10:30', '2h'),
  ('Tour de l''île à vélo', 'Parcourez les plus beaux villages et paysages de l''île en vélo.', 'L''Océan & Spa', '2025-05-20', '09:00', '5h'),
  ('Atelier dégustation d''huîtres', 'Découvrez les saveurs des huîtres locales avec un ostréiculteur passionné.', 'L''Océan & Spa', '2025-06-05', '11:00', '1h30'),
  ('Visite du phare des Baleines', 'Montez au sommet du célèbre phare pour une vue panoramique exceptionnelle.', 'L''Océan & Spa', '2025-06-15', '14:00', '2h'),
  ('Sortie observation des oiseaux', 'Explorez la réserve naturelle de Lilleau des Niges avec un ornithologue.', 'L''Océan & Spa', '2025-06-25', '07:30', '3h'),
  ('Initiation au kitesurf', 'Découvrez les bases du kitesurf avec des moniteurs professionnels.', 'L''Océan & Spa', '2025-07-05', '10:00', '3h'),
  ('Excursion à La Rochelle', 'Journée découverte de la ville historique de La Rochelle et son aquarium.', 'L''Océan & Spa', '2025-07-20', '09:00', '8h'),
  ('Soirée fruits de mer', 'Dégustez un plateau de fruits de mer accompagné des meilleurs vins locaux.', 'L''Océan & Spa', '2025-08-01', '19:30', '2h30'),
  ('Atelier cuisine régionale', 'Apprenez à préparer les spécialités culinaires de l''île de Ré.', 'L''Océan & Spa', '2025-08-10', '16:00', '3h'),
  ('Croisière au coucher du soleil', 'Naviguez autour de l''île pour admirer un magnifique coucher de soleil.', 'L''Océan & Spa', '2025-08-20', '20:00', '2h'),
  
  -- Palmyre Loisirs (Palmyre Loisirs)
  ('Animation pour enfants', 'Chasse au trésor thématique dans le camping pour les enfants de 5 à 12 ans.', 'Palmyre Loisirs', '2025-08-20', '15:00', '2h'),
  ('Tournoi de beach-volley', 'Compétition amicale de beach-volley ouverte à tous les campeurs.', 'Palmyre Loisirs', '2025-08-22', '16:00', '3h'),
  ('Soirée dansante', 'Soirée musicale avec DJ et danses pour tous les âges.', 'Palmyre Loisirs', '2025-08-24', '21:00', '3h'),
  ('Visite guidée du zoo de La Palmyre', 'Découvrez l''un des plus grands zoos privés d''Europe avec un guide.', 'Palmyre Loisirs', '2025-05-15', '10:00', '4h'),
  ('Excursion en canoë dans les marais', 'Naviguez dans les marais de la Seudre et découvrez leur écosystème unique.', 'Palmyre Loisirs', '2025-05-25', '14:00', '3h'),
  ('Atelier cuisine régionale', 'Apprenez à préparer les spécialités charentaises avec un chef local.', 'Palmyre Loisirs', '2025-06-05', '16:00', '2h30'),
  ('Randonnée à vélo dans la forêt de la Coubre', 'Explorez cette magnifique forêt de pins maritimes à vélo.', 'Palmyre Loisirs', '2025-06-15', '09:30', '3h'),
  ('Initiation à la voile', 'Découvrez les bases de la navigation à voile dans la baie de Bonne Anse.', 'Palmyre Loisirs', '2025-07-01', '10:00', '3h'),
  ('Visite des carrelets traditionnels', 'Découvrez ces cabanes de pêche typiques de la région et leur fonctionnement.', 'Palmyre Loisirs', '2025-07-10', '17:00', '2h'),
  ('Excursion à Royan', 'Journée découverte de la ville de Royan, son architecture et ses plages.', 'Palmyre Loisirs', '2025-07-20', '09:00', '6h'),
  ('Observation des étoiles', 'Soirée astronomie avec télescopes sur la plage de La Palmyre.', 'Palmyre Loisirs', '2025-08-05', '22:00', '2h'),
  ('Tournoi de mini-golf', 'Compétition amicale sur le parcours de mini-golf du camping.', 'Palmyre Loisirs', '2025-08-15', '16:00', '2h'),
  ('Atelier créatif coquillages', 'Créez des souvenirs originaux avec les coquillages ramassés sur la plage.', 'Palmyre Loisirs', '2025-08-28', '15:00', '2h'),
  
  -- Bela Basque (Bela Basque)
  ('Cours de surf avancé', 'Perfectionnez votre technique de surf avec nos moniteurs professionnels.', 'Bela Basque', '2025-07-25', '09:00', '2h'),
  ('Dégustation de tapas basques', 'Découverte des saveurs de la gastronomie basque avec dégustation de pintxos traditionnels.', 'Bela Basque', '2025-07-27', '19:00', '2h'),
  ('Excursion à San Sebastian', 'Journée découverte de cette magnifique ville espagnole réputée pour sa gastronomie.', 'Bela Basque', '2025-07-29', '08:00', '10h'),
  ('Initiation à la pelote basque', 'Découvrez ce sport traditionnel emblématique du Pays Basque.', 'Bela Basque', '2025-05-15', '16:00', '2h'),
  ('Randonnée dans les montagnes basques', 'Excursion guidée dans les contreforts des Pyrénées avec panoramas exceptionnels.', 'Bela Basque', '2025-05-25', '08:30', '6h'),
  ('Visite d''une cidrerie traditionnelle', 'Découvrez la fabrication du cidre basque suivie d''une dégustation.', 'Bela Basque', '2025-06-05', '11:00', '2h30'),
  ('Cours de cuisine basque', 'Apprenez à préparer des plats typiques de la gastronomie basque.', 'Bela Basque', '2025-06-15', '15:00', '3h'),
  ('Balade en bateau dans la baie de Saint-Jean-de-Luz', 'Découvrez la côte basque depuis la mer et ses magnifiques panoramas.', 'Bela Basque', '2025-06-25', '10:00', '2h'),
  ('Excursion à Biarritz', 'Journée découverte de cette élégante station balnéaire et son histoire.', 'Bela Basque', '2025-07-05', '09:30', '5h'),
  ('Concert de musique basque', 'Soirée musicale avec des artistes locaux jouant de la musique traditionnelle basque.', 'Bela Basque', '2025-07-15', '21:00', '2h'),
  ('Tournoi de beach rugby', 'Compétition amicale de rugby sur la plage, sport très populaire dans la région.', 'Bela Basque', '2025-08-05', '16:00', '3h'),
  ('Visite guidée du musée basque', 'Découvrez l''histoire et la culture basque à travers cette visite passionnante.', 'Bela Basque', '2025-08-15', '10:00', '2h'),
  ('Initiation au bodyboard', 'Découvrez les sensations du bodyboard sur les vagues d''Bela Basque.', 'Bela Basque', '2025-08-25', '11:00', '2h'),
  
  -- Les Truffières de Dordogne (Les Truffières de Dordogne)
  ('Chasse aux truffes', 'Partez à la recherche de truffes avec un chien truffier et son maître expérimenté.', 'Les Truffières de Dordogne', '2025-08-01', '10:00', '2h'),
  ('Atelier cuisine aux truffes', 'Apprenez à cuisiner et sublimer la truffe dans différentes recettes avec notre chef.', 'Les Truffières de Dordogne', '2025-08-03', '16:00', '3h'),
  ('Visite de château médiéval', 'Excursion guidée d''un des plus beaux châteaux de la région avec dégustation de vins locaux.', 'Les Truffières de Dordogne', '2025-08-05', '14:00', '4h'),
  ('Randonnée dans la vallée de la Dordogne', 'Découvrez les paysages exceptionnels de la vallée avec un guide nature.', 'Les Truffières de Dordogne', '2025-05-15', '09:00', '4h'),
  ('Visite d''une ferme de canards', 'Découvrez l''élevage traditionnel et la préparation du foie gras.', 'Les Truffières de Dordogne', '2025-05-25', '10:30', '2h'),
  ('Initiation à la pêche en rivière', 'Apprenez les techniques de pêche dans les eaux cristallines de la Dordogne.', 'Les Truffières de Dordogne', '2025-06-05', '07:00', '3h'),
  ('Excursion en canoë sur la Dordogne', 'Naviguez sur cette rivière magnifique et découvrez ses châteaux depuis l''eau.', 'Les Truffières de Dordogne', '2025-06-15', '10:00', '4h'),
  ('Visite de Sarlat', 'Découverte guidée de cette magnifique cité médiévale et son marché.', 'Les Truffières de Dordogne', '2025-06-25', '09:00', '5h'),
  ('Atelier poterie traditionnelle', 'Initiez-vous à l''art de la poterie avec un artisan local.', 'Les Truffières de Dordogne', '2025-07-05', '15:00', '2h30'),
  ('Dégustation de vins de Bergerac', 'Découvrez les vins locaux avec explications d''un vigneron passionné.', 'Les Truffières de Dordogne', '2025-07-15', '18:00', '2h'),
  ('Visite des jardins de Marqueyssac', 'Explorez ces jardins suspendus exceptionnels avec vue panoramique sur la vallée.', 'Les Truffières de Dordogne', '2025-07-25', '14:00', '3h'),
  ('Soirée gastronomie périgourdine', 'Dégustez les spécialités culinaires de la région lors d''un repas festif.', 'Les Truffières de Dordogne', '2025-08-15', '19:30', '3h'),
  ('Atelier fabrication de foie gras', 'Apprenez à préparer le véritable foie gras du Périgord.', 'Les Truffières de Dordogne', '2025-08-25', '16:00', '2h'),
  
  -- L'Étoile de Mer (L''Étoile de Mer)
  ('Tournoi de pétanque', 'Compétition amicale de pétanque ouverte à tous les résidents du camping.', 'L''Étoile de Mer', '2025-07-18', '17:00', '2h'),
  ('Soirée fruits de mer', 'Dégustation de plateaux de fruits de mer fraîchement pêchés accompagnés de vins locaux.', 'L''Étoile de Mer', '2025-07-20', '19:30', '3h'),
  ('Excursion au Canal du Midi', 'Découverte d''une partie du Canal du Midi en bateau avec guide et déjeuner inclus.', 'L''Étoile de Mer', '2025-07-22', '09:00', '6h'),
  ('Visite des vignobles locaux', 'Découvrez les domaines viticoles du Languedoc avec dégustation.', 'L''Étoile de Mer', '2025-05-15', '14:00', '4h'),
  ('Randonnée dans les collines de l''arrière-pays', 'Explorez les paysages méditerranéens avec un guide naturaliste.', 'L''Étoile de Mer', '2025-05-25', '09:00', '3h30'),
  ('Initiation à la planche à voile', 'Découvrez les bases de la planche à voile avec nos moniteurs diplômés.', 'L''Étoile de Mer', '2025-06-05', '10:30', '2h'),
  ('Visite du marché de Béziers', 'Découverte des produits régionaux dans l''un des plus beaux marchés de la région.', 'L''Étoile de Mer', '2025-06-15', '09:00', '3h'),
  ('Atelier cuisine méditerranéenne', 'Apprenez à préparer des plats typiques de la cuisine languedocienne.', 'L''Étoile de Mer', '2025-06-25', '16:00', '2h30'),
  ('Excursion à Sète', 'Journée découverte de cette ville maritime authentique et ses traditions.', 'L''Étoile de Mer', '2025-07-05', '09:00', '7h'),
  ('Soirée dansante flamenco', 'Soirée festive autour des danses et musiques espagnoles.', 'L''Étoile de Mer', '2025-07-15', '21:00', '2h30'),
  ('Cours de paddle yoga', 'Expérience unique combinant yoga et stand-up paddle sur la mer.', 'L''Étoile de Mer', '2025-08-05', '08:00', '1h30'),
  ('Observation des flamants roses', 'Excursion dans les étangs protégés pour observer ces oiseaux emblématiques.', 'L''Étoile de Mer', '2025-08-15', '07:00', '3h'),
  ('Balade en bateau avec fond de verre', 'Découvrez les fonds marins de la Méditerranée sans vous mouiller.', 'L''Étoile de Mer', '2025-08-25', '10:00', '1h30'); 